apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: observability
spec:
  strategy: allInOne  # For production, you might want to use "production" strategy
  allInOne:
    image: jaegertracing/all-in-one:1.44
    options:
      log-level: info
  storage:
    type: memory  # For production, consider elasticsearch
    options:
      memory:
        max-traces: 100000
  ingress:
    enabled: true
  ui:
    options:
      dependencies:
        menuEnabled: true
      tracking:
        gaID: UA-000000-2
      menu:
      - label: About Jaeger
        items:
        - label: Documentation
          url: https://www.jaegertracing.io/docs/latest
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
