apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      scrape_timeout: 10s
    
    # Alertmanager configuration
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alertmanager.monitoring.svc.cluster.local:9093
    
    # Load rules once and periodically evaluate them
    rule_files:
    - rules/alert.rules.yml
    - rules/recording.rules.yml
    
    # Scrape configurations
    scrape_configs:
      # Scrape Prometheus itself
    - job_name: prometheus
      metrics_path: /metrics
      static_configs:
      - targets: [localhost:9090]
    
      # Direct scrape of ASR API service using known endpoints
    - job_name: asr-api-direct
      metrics_path: /metrics
      scrape_interval: 5s
      scrape_timeout: 5s
      static_configs:
      - targets:
        - asr-api.asr-system.svc.cluster.local:80
      relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: (.*)
        replacement: asr-api
    
      # Kubernetes pod discovery for ASR API
    - job_name: asr-api
      metrics_path: /metrics
      scrape_interval: 5s
      scrape_timeout: 5s
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - asr-system
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: asr-api
        action: keep
      - source_labels: [__meta_kubernetes_pod_ip]
        action: replace
        target_label: __address__
        regex: (.*)
        replacement: $1:8000
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: instance
    
      # Scrape Node metrics using Kubernetes node discovery
    - job_name: kubernetes-nodes
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - source_labels: [__meta_kubernetes_node_name]
        action: replace
        target_label: instance
    
      # Scrape Jaeger
    - job_name: jaeger
      scrape_interval: 10s
      static_configs:
      - targets: [jaeger-query.observability.svc.cluster.local:14269]
    
      # Scrape Grafana
    - job_name: grafana
      scrape_interval: 10s
      static_configs:
      - targets: [grafana.monitoring.svc.cluster.local:3000]
      
  # Rules
  alert.rules.yml: |
    groups:
    - name: ASR Alerts
      rules:
      - alert: HighRequestLatency
        expr: request_duration_seconds{quantile="0.9"} > 1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High request latency"
          description: "ASR API has high request latency (90th percentile > 1s)"
      
      - alert: HighErrorRate
        expr: sum(rate(http_requests_total{status=~"5.*"}[5m])) / sum(rate(http_requests_total[5m])) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate"
          description: "ASR API error rate is above 10%"
          
  recording.rules.yml: |
    groups:
    - name: ASR Recording Rules
      interval: 30s
      rules:
      - record: asr:request_duration:avg_5m
        expr: avg(rate(request_duration_seconds_sum[5m]) / rate(request_duration_seconds_count[5m]))
      
      - record: asr:request_rate:avg_5m
        expr: sum(rate(http_requests_total[5m])) 