[tool.black]
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | checkpoints
  | dist
  | venv
)/
'''
include = '\.pyi?$'
line-length = 100
target-version = ['py310']

[tool.isort]
include_trailing_comma = true
known_first_party = [
  "api",
  "src",
  "ui"
]
known_third_party = [
  "torch",
  "numpy",
  "fastapi",
  "streamlit",
  "transformers",
  "huggingface_hub",
  "pydantic"
]
line_length = 100
multi_line_output = 3
profile = "black"

[tool.mypy]
check_untyped_defs = true
disallow_incomplete_defs = false
disallow_untyped_decorators = false
disallow_untyped_defs = false
no_implicit_optional = true
python_version = "3.10"
strict_optional = true
warn_return_any = true
warn_unused_configs = true

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = [
  "torch.*",
  "numpy.*",
  "transformers.*",
  "huggingface_hub.*",
  "librosa.*",
  "torchaudio.*",
  "soundfile.*"
]
