apiVersion: v1
kind: Service
metadata:
  name: speech-api-service
  labels:
    app: speech-api
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: speech-api
