apiVersion: v1
kind: Pod
metadata:
  name: asr-test-pod
  namespace: asr-system
  labels:
    app: asr-test
spec:
  containers:
  - name: asr-test
    image: tuandung12092002/asr-fastapi-server:latest
    imagePullPolicy: Always
    # # Override the command to provide an interactive shell
    # command: ["sleep", "3600"]  # Keep the container running for 1 hour
    
    # Environment variables matching the API deployment
    env:
    - name: PYTHONPATH
      value: "/app"
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: PYTHONDONTWRITEBYTECODE
      value: "1"
    - name: PORT
      value: "8000"
    - name: INFERENCE_DEVICE
      value: "cpu"
    - name: ENVIRONMENT
      value: "testing"
    
    # Volume mounts matching the API deployment
    volumeMounts:
    - name: prometheus-metrics
      mountPath: /tmp/prometheus-metrics
    
    # Resource requests/limits (reduced for test pod)
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 2Gi
        cpu: 2000m
  
  # Volumes matching the API deployment
  volumes:
  - name: prometheus-metrics
    emptyDir: {}
  
  # Run for 1 hour maximum, then terminate
  terminationGracePeriodSeconds: 30
  restartPolicy: Never 