apiVersion: apps/v1
kind: Deployment
metadata:
  name: asr-api
  labels:
    app: asr-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: asr-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: asr-api
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8000'
        prometheus.io/path: /metrics
    spec:
      containers:
      - name: asr-api
        image: vietnamese-asr:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: '4'
            memory: 8Gi
            nvidia.com/gpu: 1
          requests:
            cpu: '2'
            memory: 4Gi
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: asr-api-config
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 20
        volumeMounts:
        - name: model-cache
          mountPath: /app/models
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: model-cache
        emptyDir:
          sizeLimit: 10Gi
      - name: tmp-volume
        emptyDir:
          sizeLimit: 1Gi
