version: '3.8'

services:
  # Prometheus for metrics
  prometheus:
    image: prom/prometheus:v2.46.0
    ports:
    - 9090:9090
    volumes:
    - ./monitoring/prometheus:/etc/prometheus
    - prometheus_data:/prometheus
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --storage.tsdb.retention.time=15d
    - --web.console.libraries=/usr/share/prometheus/console_libraries
    - --web.console.templates=/usr/share/prometheus/consoles
    - --web.enable-lifecycle
    - --web.enable-admin-api
    - --web.external-url=http://localhost:9090
    restart: unless-stopped
    networks:
    - asr-network
    user: nobody:nobody
    extra_hosts:
    - host.docker.internal:host-gateway

  # AlertManager for alert management
  alertmanager:
    image: prom/alertmanager:v0.26.0
    ports:
    - 9093:9093
    volumes:
    - ./monitoring/alertmanager:/etc/alertmanager
    command:
    - --config.file=/etc/alertmanager/alertmanager.yml
    - --storage.path=/alertmanager
    - --web.external-url=http://localhost:9093
    restart: unless-stopped
    networks:
    - asr-network
    user: nobody:nobody

  # Grafana for dashboards
  grafana:
    image: grafana/grafana:10.2.3
    ports:
    - 3000:3000
    volumes:
    - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    - grafana_data:/var/lib/grafana
    environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=F7aJw3kQ9pL5xYzR
    - GF_USERS_ALLOW_SIGN_UP=false
    - GF_SERVER_ROOT_URL=http://localhost:3000
    - GF_SERVER_DOMAIN=localhost
    - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel
    - GF_AUTH_ANONYMOUS_ENABLED=false
    - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
    - GF_UNIFIED_ALERTING_UI_DISABLE_REPROVISION=true
    depends_on:
    - prometheus
    restart: unless-stopped
    networks:
    - asr-network

  # Jaeger for distributed tracing
  jaeger:
    image: jaegertracing/all-in-one:1.48
    ports:
    - 6831:6831/udp      # accept jaeger.thrift over compact thrift protocol
    - 6832:6832/udp      # accept jaeger.thrift over binary thrift protocol
    - 16686:16686        # UI port
    - 14268:14268        # HTTP Collector
    environment:
    - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    - COLLECTOR_OTLP_ENABLED=true
    - JAEGER_DISABLED=false
    - SPAN_STORAGE_TYPE=memory
    - METRICS_STORAGE_TYPE=prometheus
    - PROMETHEUS_SERVER_URL=http://prometheus:9090
    - SAMPLING_STRATEGIES_FILE=/etc/jaeger/sampling.json
    volumes:
    - ./monitoring/jaeger:/etc/jaeger
    restart: unless-stopped
    networks:
    - asr-network

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  asr-network:
    driver: bridge
