apiVersion: v1
kind: Service
metadata:
  name: asr-ui
  namespace: asr-system
  labels:
    app: asr-ui
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: asr-ui-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8501
    protocol: TCP
    name: http
  selector:
    app: asr-ui
